name: bks
description: "manajemen keuangan bos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  currency_text_input_formatter: ^2.3.0
  excel: ^4.0.6
  file_saver: ^0.2.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_slidable: ^4.0.3
  intl: ^0.20.2
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pattern_formatter: ^4.0.1
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
